### ISSUE TITLE
Resolving variable names

### ISSUE THREAD

**Issue by Kaffedreng** [benc-uk/armview-vscode#38] opened 2020-10-26 12:43 UTC
**Is your feature request related to a problem? Please describe.**
Resolving names based on variables. It's not as much of a problem, more a nice to have feature.

**Describe the solution you'd like**
I would like to see that my variables, when labels are shown or in general, will be resolved from the current `format(variables('longName'), 'kv', '001')` to `kv-namingconvention-001`, as demonstrated below:
```
"parameters": {
    "NamingConvention": {
        "type": "string",
        "defaultValue": "{0}-namingconvention-{1}",
    }
}

"variables": {
    "longName": "[parameters('NamingConvention')]",
    "storageAccount": "[replace(tolower(format(variables('longName'), 'st', '001')), '-', '')]",
    "keyVaultName": "[format(variables('longName'), 'kv', '001')]"
}
```

Resolved names:
`stnamingconvention001`
`kv-namingconvention-001`

Please do let me know if a better description is needed!

**Comment by benc-uk** [comment] 2020-11-23 12:14
It does support resolving variables, I think the issue is the extension doesn't support the `format()` function
I'll investigate

**Comment by benc-uk** [comment] 2022-02-06 00:53
I will not be adding support for format(), sorry

**Closed as completed by benc-uk** 2022-02-06 00:53 UTC
Labels: enhancement
