### ISSUE TITLE
Database dependency not picked up

### ISSUE THREAD

**Issue by simonech** [benc-uk/armview-vscode#33] opened 2020-10-07 10:37 UTC
**Describe the bug**
My ARM template has a website which `dependsOn` a SQL Database (and a few other resources).
The other resources are displayed, but not the database connection

**To Reproduce**

```
            "dependsOn": [
                "[resourceId('Microsoft.Insights/components/', variables('appInsight'))]",
                "[resourceId('Microsoft.Web/serverfarms/', variables('hostingPlanName'))]",
                "[resourceId('Microsoft.Sql/servers/databases/', variables('dbServerName'), variables('dbName'))]"
            ],
```

![image](https://user-images.githubusercontent.com/61557/95320349-a9663b80-0899-11eb-840b-e40dac398502.png)

I understand there are "known issues" with the `dependsOn` but here the 3 resources are expressed in the same way.

If not possible to fix, could you please tell me how to express that dependency so that it gets picked up?

**Comment by benc-uk** [comment] 2020-10-21 10:36
Hi, Thanks for bringing this to my attention. I was able to reproduce. It's because resources like databases are normally defined as nested resources. If you move the to the top level resource array my extension would show this links

Anyhow it was a very deep bug in how I parse the dependsOn links, which has been in the code for a very long time, so I'm surprised it hasn't been raised before!

Should be fixed in the next release

**Closed as completed** 2020-10-21 13:45 UTC
